name: Indicadores_financieros

on:
  push:
    branches: [ main ]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout del repo
        uses: actions/checkout@v4
      - name: checkout del repo
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.13'
      - name: actualizar pip
        run: pip install --upgrade pip
      - name: instalacion dependencias
        run: pip install -r requeriments.txt
      - name: Instalar el paquete en modo editable
        run: pip install -e .
      - name: Listar archivos y verificar existencia de ejecucion.py
        run: |
          ls -R
          if [ ! -f "src/actividad/ejecucion.py" ]; then
            echo "El archivo src/actividad/ejecucion.py no se encontró."
            exit 1
          fi
      - name: ejecutar scripts
        run: python src/actividad/ejecucion.py

      - name: Commit and push changes
        uses: actions/checkout@v4
        with: 
          commit_user_name: Andres Callejas
          commit_user_email: andres.callejas@iudigital.edu.co
          commit_author: andresfkyjas
          
          

      
